version: '3.6'
name: hermes

networks:
  traefik-proxy:
    external:
      true

  internal:
    external:
      false

volumes:
  db_data:

services:
  hermes-postgres:
    image: postgres:12
    container_name: hermes-postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - internal
  
  hermes-hasura:
    image: hasura/graphql-engine:v2.9.0
    container_name: hermes-hasura
    depends_on:
    - "hermes-postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@hermes-postgres/${POSTGRES_DB}
      PG_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      # HASURA_GRAPHQL_AUTH_HOOK: http://hermes-token-server:3001/validate-token
    networks:
      - internal
      - traefik-proxy
    ports:
      - "8080:8080"
    labels:
      # - traefik.http.routers.hermes-hasura.tls=${TLS}
      # - traefik.http.routers.hermes-hasura.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.hermes-hasura.entrypoints=${ENTRYPOINTS}
      - traefik.http.routers.hermes-hasura.rule=Host(`${URL_PREFIX}.hermes-hasura.${URL_POSFIX}`)
      - traefik.http.services.hermes-hasura.loadbalancer.server.port=8080
    
  # hermes-token-server:
  #   container_name: hermes-token-server
  #   build: 
  #     context: ./token-server
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - PORT=3001
  #   networks:
  #     - internal
  #     - traefik-proxy

  # hermes-backend:
  #   container_name: hermes-backend
  #   build: 
  #     context:
  #       ./backend
  #   networks:
  #     - internal
  #     - traefik-proxy
  #   labels:
  #     # - traefik.http.routers.hermes-backend.tls=${TLS}
  #     - traefik.http.routers.hermes-backend.entrypoints=websecure
  #     - traefik.http.routers.hermes-backend.rule=Host(`${URL_PREFIX}.hermes-backend.${URL_POSFIX}`)
  #     - traefik.http.routers.hermes-backend.tls.certresolver=${CERT_RESOLVER}
  #     - traefik.http.services.hermes-backend.loadbalancer.server.port=${BACKEND_PORT}
  
  # hermes-frontend:
  #   container_name: hermes-frontend
  #   build:
  #     context: 
  #       ./frontend
  #   networks:
  #     - internal
  #     - traefik-proxy
  #   labels:
  #     # - traefik.http.routers.hermes-frontend.tls=${TLS}
  #     # - traefik.http.routers.hermes-frontend.tls.certresolver=${CERT_RESOLVER}
  #     - traefik.http.routers.hermes-frontend.rule=Host(`${URL_PREFIX}.hermes-frontend.${URL_POSFIX}`)
  #     - traefik.http.routers.hermes-frontend.entrypoints=${ENTRYPOINTS}
  #     - traefik.http.services.hermes-frontend.loadbalancer.server.port=${FRONTEND_PORT}
    
